version: "3.8"

services:
  pgvector-db:
    image: pgvector/pgvector:0.8.0-pg17
    container_name: pgvector-db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5431:5432"
    volumes:
      - pgvector-data:/var/lib/postgresql/data

volumes:
  pgvector-data:
