# docker-compose.yml
version: '3.8'

services:
  postgres:
    image: postgres:13-alpine3.20
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    restart: always

volumes:
  postgres_data:
